### ISSUE TITLE
Generated project's test:e2e causes Error: kill EPERM.

### ISSUE THREAD

**Issue by MeirionHughes** [vuejs/create-vue#539] opened 2024-06-28 09:30 UTC
I'm not sure where this bug report should go. This seemed like logical place as the generated project's test:e2e just fails. my guess is a change in vite causing start-server-and-test to fail. 

### Describe the bug

the generated project's e2e test when using cypress and start-server-and-test fails with Error: kill EPERM. 

```
Child process 24584 exited before trying to stop it
Error: kill EPERM
    at process.kill (node:internal/process/per_thread:228:13)
    at D:\testing\vue-project\node_modules\start-server-and-test\src\index.js:62:23
    at Array.forEach (<anonymous>)
    at D:\testing\vue-project\node_modules\start-server-and-test\src\index.js:60:20
    at tryCatcher (D:\testing\vue-project\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\testing\vue-project\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (D:\testing\vue-project\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (D:\testing\vue-project\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (D:\testing\vue-project\node_modules\bluebird\js\release\promise.js:729:18)
    at Promise._fulfill (D:\testing\vue-project\node_modules\bluebird\js\release\promise.js:673:18)
    at D:\testing\vue-project\node_modules\bluebird\js\release\nodeback.js:42:21
    at D:\testing\vue-project\node_modules\ps-tree\index.js:87:7
    at a.end (D:\testing\vue-project\node_modules\event-stream\index.js:87:5)
    at Stream.onend (node:internal/streams/legacy:48:10)
    at Stream.emit (node:events:531:35)
    at end (D:\testing\vue-project\node_modules\map-stream\index.js:116:39) {
  errno: -4048,
  code: 'EPERM',
  syscall: 'kill'
}
```

### repo

* npm create vue@latest
* No for everything - choose cypress. 
* npm install 
* npm run build
* npm run test:e2e 

run the test a few times as it can be a race-condition. 

shell: windows 11, cmd or ps 
node -v  : 21.7.3 and 22.3.0
electron (cypress) 118
npm why start-server-and-test : start-server-and-test@2.0.4 
npm why vite : vite@5.3.2 
npm why cypress: cypress@13.12.0

**Comment by MeirionHughes** [comment] 2024-06-28 09:38
possibly related: https://github.com/bahmutov/start-server-and-test/issues/199

**Comment by Yordan-Ramchev** [comment] 2024-06-28 09:55
I could not reproduce this error, but I am using node v20.12.1, I will try later with node v22 (maybe that is causing the issue)
<img width="785" alt="Screenshot 2024-06-28 at 12 51 30" src="https://github.com/vuejs/create-vue/assets/69005114/53c2d8b7-12fa-40d7-98e5-86dea1c55708">

**Comment by MeirionHughes** [comment] 2024-06-28 10:00
If I go to node v20.15.0 I don't get the error, but I do get: 

```
Child process 16072 exited before trying to stop it
Child process 27140 exited before trying to stop it
```

but it does complete without error even after a few tries

**Comment by cexbrayat** [comment] 2024-06-28 10:10
Hi @MeirionHughes 

To be honest, I don't think there is anything we can do in create-vue for this issue: it does look like this is specific to windows/node and cypress or start-server-and-test. I'm going to close this issue, and maybe you can try to reproduce it with a brand new project (using just vite and cypress) and open an issue on the cypress or start-server-and-test repositories.

**Closed by cexbrayat** 2024-06-28 10:10 UTC
Labels: bug

**Comment by MeirionHughes** [comment] 2024-06-28 11:38
Okay, kicked it over start-server-and-test https://github.com/bahmutov/start-server-and-test/issues/384
