### ISSUE TITLE
Doesn't shows TS errors

### ISSUE THREAD

**Issue by apuatcfbd** [vuejs/create-vue#290] opened 2023-06-01 13:08 UTC
I've explained the issue in [StackOverflow](https://stackoverflow.com/questions/76380652/vue-3-typescript-not-working-properly-in-template-section)

The issue in short:
`ComponentA` has prop `duration` accepts only '`1'|'2'|...`
When `ComponentA` is used in other components like `<ComponentA duration="7"` it doesn't show any error.

Googled it but didn't find any solution that are working for me.

**Comment by sodatea** [comment] 2023-06-12 10:10
I can't be sure because no runnable reproduction is provided.

But you might have encountered this issue with TypeScript 5.1.3: https://github.com/vuejs/language-tools/issues/3268
Please make sure you are using the workspace version of TypeScript (~5.0.4) rather than VS Code's version (5.1.3) in the editor.
You can check this by typing "Select TypeScript version" in the VS Code command palette.
<img width="598" alt="image" src="https://github.com/vuejs/create-vue/assets/3277634/635b50f8-8576-4142-a5ba-dfa397a977e2">
<img width="615" alt="image" src="https://github.com/vuejs/create-vue/assets/3277634/4791c7ce-3bae-49f6-86a2-a5ee28caa4fc">

**Comment by sodatea** [comment] 2023-06-21 07:54
It's fixed in the latest `vue-tsc` version (1.8.1).

**Closed by sodatea** 2023-06-21 07:54 UTC
Labels: upstream

**Comment by apudiu** [comment] 2023-06-23 09:18
@sodatea thank you,
FYI: I'm using PhpStorm (not VS Code)
