### ISSUE TITLE
The engine "node" is incompatible with this module. Expected version "8 || 10 || 12 || 14 || 16 || 17". Got "18.12.1"

### ISSUE THREAD

**Issue by 9mm** [vuejs/create-vue#217] opened 2023-01-05 04:45 UTC
```
error @achrinza/node-ipc@9.2.2: The engine "node" is incompatible with this module. Expected version "8 || 10 || 12 || 14 || 16 || 17". Got "18.12.1"
error Found incompatible module.
```

Do you know why I must use node 17 and node 19 is already out? This happens regularly and is super and is quite annoying, I feel like every vue project i create I must deal with this

I did try --ignore-engines and that doesnt work either with the `yarn create` command. I tried doing `yarn global add vue@3` but it says it has no binaries, and create-vue does not work

**Comment by 9mm** [comment] 2023-01-05 04:46
If I do `nvm use 17` I get this:

```
➜  ~ yarn create vue@3
yarn create v1.22.19
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...

success Installed "create-vue@3.5.0" with binaries:
      - create-vue
/bin/sh: /usr/local/bin/create-vue@3: No such file or directory
error Command failed.
Exit code: 127
Command: /usr/local/bin/create-vue@3
Arguments:
Directory: /Users/me
Output:
```

**Comment by sodatea** [comment] 2023-01-05 06:28
But this project does not depend on `@achrinza/node-ipc`. Could you provide a reproduction?

**Comment by sodatea** [comment] 2023-01-05 06:29
Have you ever installed an outdated version of `@vue/cli` globally?

**Comment by 9mm** [comment] 2023-01-05 14:15
hmm that is possible, maybe yarn global is whining about another package even though im not specifically calling it? I wouldnt have thought it would prevent me from doing `yarn create vue@3` though, which is quite weird

**Comment by sodatea** [comment] 2023-02-23 14:23
I'm closing this issue for now as there are no other similar reports, and according to the current information, there's nothing we can do on our side.

**Closed by sodatea** 2023-02-23 14:23 UTC
Labels: needs reproduction

**Comment by gerbenoostra** [comment] 2024-01-12 17:01
> Have you ever installed an outdated version of `@vue/cli` globally?

This, I wanted to try to scaffold a new vue3 project and ran into this,\
`yarn create vue@latest` and it fails with `error @achrinza/node-ipc@9.2.2: The engine "node" is incompatible with this module. Expected version "8 || 10 || 12 || 14 || 16 || 17". Got "`

Would be good to add a note on the getting started page that old vue / vue-.. versions might conflict

**Comment by adrian-martinez-dev** [comment] 2024-05-14 18:14
I'm dealing with this issue, have anyone found a way to solve it?

**Comment by Yordan-Ramchev** [comment] 2024-05-14 18:20
@adrian-martinez-dev Is it yarn related? If so what version of yarn do you use? If it's lower than v2, can you try upgrading to newer one, because latest is 4.2.2 - https://yarnpkg.com/getting-started

**Comment by adrian-martinez-dev** [comment] 2024-05-14 18:26
Hi, I'm trying with yarn 1.22 and node 20, I'll upgrade yarn, thanks

**Comment by adrian-martinez-dev** [comment] 2024-05-14 18:28
@Yordan-Ramchev fixed by running `yarn set version stable`
